blank_issues_enabled: false
contact_links:
  - name: Question or help request
    url: https://github.com/nestql/prisma-crud/discussions
    about: Github Discussions is the place to ask a question or discuss with other community members
